"use strict";
// web developer
new TypeIt(".home__title--strong", { loop: true, speed: 100 })
  .move(-13)
  .type("Amazing ")
  .pause(1000)
  .move(null, { to: "END" })
  .delete()
  .type("Front-End Engineer")
  .pause(1000)
  .move(-9)
  .delete(9)
  .type("Back-End")
  .pause(1000)
  .move(null, { to: "END" })
  .delete()
  .type("Entivel CIO")
  .pause(1000)
  .delete()
  .go();
